# Autogenerated wrapper script for cephes_jll for aarch64-apple-darwin
export libcephes

JLLWrappers.@generate_wrapper_header("cephes")
JLLWrappers.@declare_library_product(libcephes, "@rpath/libcephes.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcephes,
        "lib/libcephes.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
