# Autogenerated wrapper script for cephes_jll for armv7l-linux-gnueabihf
export libcephes

JLLWrappers.@generate_wrapper_header("cephes")
JLLWrappers.@declare_library_product(libcephes, "libcephes.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcephes,
        "lib/libcephes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
