# Autogenerated wrapper script for cephes_jll for x86_64-w64-mingw32
export libcephes

JLLWrappers.@generate_wrapper_header("cephes")
JLLWrappers.@declare_library_product(libcephes, "libcephes.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcephes,
        "bin\\libcephes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
